language: ruby

services:
  - postgresql

rvm:
  - 2.6.3

install:
  - gem install rubocop

script:
  - rubocop
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
